release-engineering/rhtap-ec-policy

- data/required_tasks.yml
With the fix from https://issues.redhat.com/browse/EC-53, the process of determining the list of required tasks is now correctly taking into account the labels on the build task. As such, the "docker" type is now used.
> Provide required tasks for docker pipelines

- data/required_tasks.yml
The task is removed from all pipelines and then explicitly added to the FBC pipeline in
https://github.com/redhat-appstudio/build-definitions/pull/630. This PR is to ensure that the change can pass EC checks.
> The inspect-image task is only required as part of the FBC pipeline

- data/required_tasks.yml
With the https://github.com/enterprise-contract/ec-policies/pull/789 merged we can support 'one of' semantic in required task. This changes the definition of required tasks so one of buildah task variants is required.
reference: https://issues.redhat.com/browse/RHTAPBUGS-914
> Add all variants of buildah task

- data/required_tasks.yml
> Add missing buildah variants

- data/required_tasks.yml
This commit adds `source-build` as a required task to pipeline-required-tasks as appropriate.
Resolves: EC-233
> Add `source-build` as a required task to pipelines

- data/required_tasks.yml
The new policy went into effect with the new year and it doesn't contain all the variants of the buildah task. This adds them.
> Make sure to include all buildah variants

- data/rule_data.yml
As the comment suggests, the
quay.io/openshift-release-dev/ocp-v4.0-art-dev was added as a workaround to an OCP issue. The policy rule that uses this data has been moved from the "release" namespace to the "task" namespace. This means the policy rule applies to a Task definition instead of the Task information captured in the SLSA Provenance attestation. The check is now executed as part of the build-definitions CI on the Task definitions directly.
At some point, we may want to execute the check against the information in the SLSA Provenance attestation but currently this is not possible. https://issues.redhat.com/browse/RFE-4608 will hopefully turn this into reality.
> Remove irrelevant step image

- data/required_tasks.yml
FBC components are not pushed directly to the registry. Instead, they just contain data (i.e. catalog.json) which is added to the index image for use by OLM. Therefore, we do not need to require the checks which
inspect the image.
> Remove unneeded tasks from FBC

- data/required_tasks.yml
Removing the task sbom-json-check for the current set of required tasks. The EC policies should be checking for valid SBOMs anyway so this check is unnecessarily duplicated.
> Remove sbom-json-check from required tasks

- data/rule_data.yml
https://quay.io/repository/konflux-ci/oras?tab=tags&tag=latest is the first one, for https://github.com/redhat-appstudio/build-definitions/pull/992
> Allow quay.io/konflux-ci/ for step images

- data/required_tasks.yml
As part of EC-20, we are adding Task variants that support Trusted Artifacts with OCI storage. These have the suffix of `-oci-ta`. These Tasks function similarly to their counter-parts. The main difference is that they share data between them via resources in an OCI registry instead of file in a shared PVC on-cluster.
This commit allows the `-oci-ta` Tasks to fullfill the required-tasks check.
Additionally, the `summary` Task is no longer marked as required. This was the outcome after some investigation on its actual value. More context is available on the comments of EC-643.
Finally, older entries that are no longer relevant have been removed from the list.
Ref: EC-644
> Allow usage of the *-oci-ta Task variants

- data/rule_data.yml
These were added and then removed in the past because the checks were being incorrectly applied to all pipelines instead of just release pipelines.
Now we have a mechanism to distinguish between release pipelines and non-release pipelines so it should be safe to bring back these schedule restrictions.
Ref: https://issues.redhat.com/browse/EC-637
> Bring back weekend & shutdown release restrictions

- data/rule_data.yml
The sast-snyk-check test is marked as an informative test. This means it is ok if it emits failures, as long as it was able execute. There is a variation of the check that supports Trusted Artifacts.
This commit marks the sast-snyk-check-oci-ta test as an information test.
> Mark sast-snyk-check TA alternative as informative

- data/rule_data.yml
I'm not sure about the pros and cons of this, but there are several teams who get surprised by this failure and want to exclude it.
Because the task itself it not included in the required task lists, removing it entirely from the pipeline gets EC to pass. So for that reason I'm assuming it's acceptable to make it non-blocking.
(The downside is that it's going to be much easier to ignore any failures produced by this test.)
[This PR](https://github.com/konflux-ci/build-definitions/pull/556) has some useful context. The original intention was that the test should not be a hard requirement to begin with, which I think supports the goal of this PR.
> Make ecosytem preflight failures non-blocking

- data/rule_data.yml
cachi2 will set the `cachi2:pip:package:binary` property to `true` for the dependencies from pip that contain binaries within them. This in conjunction with [PR#1030][1] will not allow those.
Reference: https://issues.redhat.com/browse/EC-638
[1] https://github.com/enterprise-contract/ec-policies/pull/1030
> Disallow binary dependencies in python packages

- data/rule_data.yml
Added required_olm_features_annotations data to rule data.
It came up in an ec-policies [PR review](https://github.com/enterprise-contract/ec-policies/pull/1092#discussion_r1697515781) that `required_olm_features_annotations` was missing from the rule data.
> Add features annotations to rule data

- data/rule_data.yml
As part of EC-726, a new policy rule,
`buildah_build_task.platform_param`,  was added to prevent certain platforms from being used based on the value of the `disallowed_platform_patterns` rule data.
This commit disallows using platforms that include the `root` string. This is the convention used to specify rootful hosts.
For the workflows that do require rootful access, use a policy config that either disables the policy rule, or overrides the value of the rule data to an empty list.
Ref: EC-726
> Add disallowed_platform_patterns

- data/rule_data.yml
Currently, the EC CLI behaves differently if the vendor label is set to the value `Red Hat, Inc.`. If so, it downloads certain files from within the image and makes them available for processing by the rego policy rules. If the image uses a different value for this label then those files are not available. This often causes confusion to users and to most of us analyzing those failures. This change increases visibility for such cases.
Ref: https://issues.redhat.com/browse/EC-787
> Require specific value for vendor label

- data/rule_data.yml
This change would forbid any packages with externalReferences of type `distribution` by default. This would be done in order to restrict packages from unknown sources, particularly those fetched with cachi2's planned generic pre-fetching functionality (https://github.com/containerbuildsystem/cachi2/pull/652).
> Disallow externalReferences of type distribution by default

- data/rule_data.yml
This submodule `api` has a different license than the top-level module. Its license is more permissive thus it can be legally used.
Ref: https://issues.redhat.com/browse/EC-870
> Allow hashicorp consul/api package

- data/rule_data.yml
The hashicorp/vault module has some problematic licensing, but the submodules are MPL 2.0 so they should be okay.
Similar to #51.
Ref: https://issues.redhat.com/browse/EC-920
> Allow hashcorp/vault/{api,sdk} golang submodules

- data/required_tasks.yml
FBC images are "catalog fragments" that are never actually shipped. They only exist to convey data to the process that updates the global index image. It is unreasonable to scan them for rpm content.
Even if they somehow included unsigned rpm content, that content is never going to be exposed.
> Drop rpms-signature-scan from fbc required tasks

- data/required_tasks.yml
The show-sbom task is one that is in users' pipelines for their own benefit. There are no additional guarantees provided for the artifact based on its presence. The output of the task is not used by policies.
> remove show-sbom as a required task

- data/rule_data.yml
Related: https://issues.redhat.com/browse/OSH-716
Added redhat-services-prod prefix to the allowed step images contract policy
> added redhat-services-prod to allowed_step_image

- data/rule_data.yml
With https://issues.redhat.com/browse/EC-944 outdated task warning can be refrained until the task is to expire in a configured amount of days.
This sets that configuration setting to 14 days, so folk should not get warnings until two weeks before the task expires.
Reference: https://issues.redhat.com/browse/EC-944
> Warn of outdated tasks until 14 days prior expiry

- data/rule_data.yml
(OCI/Docker) containers have a long history, and Red Hat was there in the early days, before things were standardized as OCI even - and especially before things like manifest lists and also the standard annotation keys: https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys
There are two labels this policy requires that duplicate standard metadata.
- `architecture`: This is already handled via manifest listing and is part of the config
- `build-date`: There's a standard `Created` field
As these are basically legacy from old Red Hat build systems we are just cargo culting forward for as far as I know no good reason, let's stop doing that.
Signed-off-by: Colin Walters <walters@verbum.org>
> rules: Drop `architecture` and `build-date` from required container labels

- .github/workflows/tests.yaml
Since there's not an easy way to update ec use the rolling release.
https://issues.redhat.com/browse/EC-1066
> Using rolling release of EC

- data/rule_data.yml
We agreed that it is permissible because it is built hermetically.
> Allow quay.io/konflux-ci/yq as a base image

- data/required_tasks.yml
- data/rule_data.yml
Use an effective on date of March 1st to give people time to get them added them to their pipeline definitions.
Note the tests will be required, meaning if they're not included EC will produce a "required task not found" violation, but they are "informative" only, meaning if they produce a failure status, EC will not produce a violation.
I didn't add the new tasks to the fbc pipeline required task list since I think sast scans are likely not useful there, and because the existing sast-snyk-check scan is already not required for fbc.
Handy queries to help confirm this change:
```
yq '.pipeline-required-tasks | to_entries[].value |[.[0].tasks - .[1].tasks]' data/required_tasks.yml
yq '.required-tasks|[.[0].tasks - .[1].tasks]' data/required_tasks.yml
```
Ref: …
> Add three new sast scans to required tasks

- data/rule_data.yml
Policy violations were failing with errors like:
```
✕ [Violation] java.trusted_dependencies_source_list_provided
Reason: Rule data allowed_java_component_sources has unexpected format: (Root): Array must have at least 1 items
Title: Trusted Java dependency source list was provided
Description: Confirm the `allowed_java_component_sources` rule data was provided, since it's required by the policy rules in
this package. To exclude this rule add "java.trusted_dependencies_source_list_provided" to the `exclude` section of the policy
configuration.
Solution: Add a data source that contains allowable source repositories for build dependencies. The source must be located under
a key named 'allowed_java_component_sources'. More information on adding …
```
> allowed_java_component_sources needs at least one entry

- hack/verify-data.sh
- policy.yaml
Rather than validate the data against the very latest main branch of ec-policies, it's potentially more useful to use the same policy bundle that Konflux prod is using.
This might help reduce the chance of a data change breaking Konflux production because it depends on a fresh ec-policies change that hasn't yet rolled out.
> Use Konflux prod policy bundle to validate data

- data/required_tasks.yml
- data/rule_data.yml
CVP-4373. This commit adds fbc-fips-check as a required task to the FBC pipeline and fips-operator-bundle-check as a required task in the container pipeline. The commit also adds their repective TA versions.
> feat: add Operator FIPS Compliance checks as required tasks

- data/required_tasks.yml
The work to generate PRs to add the new SAST tasks is behind schedule. See EC-1063 for more details.
It's generally working but it's needs a bit more work and testing before it's ready for production use. Also I'd like to have the email notifications and announcements sent, and the generated PRs created, well ahead of the deadline, to give teams have enough time to respond, and so we have enough time to deal with edge cases and unexpected problems.
Ref: https://issues.redhat.com/browse/EC-1063
Ref: https://issues.redhat.com/browse/KONFLUX-2264
> Extend deadline for new sast tasks

- data/rule_data.yml
The intent of this change is prevent pipelines from failing when this task reports FAILURE status. The coverity-availability-check task is only intended to check if required secrets are present before trying to run sast-coverity-check. The coverity-availability-check task will report failure to users if the required secrets are not present, and the sast-coverity-check task will be skipped.
Based on errors like:
```
The Task "coverity-availability-check" from the build Pipeline reports a failed test Title: No tests failed Description: Produce a violation if any non-informative tests have their result set to "FAILED". The result type is configurable by the "failed_tests_results" key, and the list of informative tests is configurable by the "informative_tests" key in the rule data. To …
```
> Add coverity-availability-check to informative_tests

- data/rule_data.yml
operator-sdk-builder is an image that provides all the tooling needed to generate operator bundles. It is fully maintained by Red Hat and only contains content produced by Red Hat.
See https://github.com/konflux-ci/operator-sdk-builder
Related: [KONFLUX-5108](https://issues.redhat.com/browse/KONFLUX-5108), [EC-1295](https://issues.redhat.com/browse/EC-1295)
> Add operator-sdk-builder to allowed base imges

- data/rule_data.yml
The FBC fragments for unreleased OCP versions have to use the base image from brew - `brew.registry.redhat.io/rh-osbs/openshift-ose-operator-registry-rhel9`
It makes sense to allow it by default.
> Add FBC image from brew to prod policy
